import { Product, ProductVariant, ProductWithVariants } from "@shared/schema";
import navyShirtImg from "@assets/generated_images/Navy_blue_casual_shirt_23ea7159.png";
import whiteShirtImg from "@assets/generated_images/White_formal_dress_shirt_5e039a42.png";
import checkeredShirtImg from "@assets/generated_images/Blue_checkered_casual_shirt_8e0f7b52.png";
import poloShirtImg from "@assets/generated_images/Black_polo_shirt_13e337ec.png";

// TODO: Remove mock functionality - replace with real API data
export const mockProducts: ProductWithVariants[] = [
  {
    id: "1",
    name: "Classic Navy Casual Shirt",
    description: "Premium cotton casual shirt perfect for everyday wear. Comfortable fit with modern styling.",
    basePrice: "29.99",
    brand: "StyleCraft",
    category: "Casual",
    material: "100% Cotton",
    pattern: "Plain",
    fit: "Regular",
    sleeve: "Long",
    rating: "4.5",
    reviewCount: 128,
    images: [navyShirtImg],
    createdAt: new Date(),
    variants: [
      {
        id: "v1",
        productId: "1",
        color: "Navy",
        size: "S",
        stock: 25,
        price: "29.99",
        discountPercent: 0,
      },
      {
        id: "v2",
        productId: "1",
        color: "Navy",
        size: "M",
        stock: 30,
        price: "29.99",
        discountPercent: 0,
      },
      {
        id: "v3",
        productId: "1",
        color: "Navy",
        size: "L",
        stock: 20,
        price: "29.99",
        discountPercent: 0,
      },
      {
        id: "v4",
        productId: "1",
        color: "Navy",
        size: "XL",
        stock: 15,
        price: "29.99",
        discountPercent: 0,
      },
    ],
  },
  {
    id: "2",
    name: "Premium White Formal Shirt",
    description: "Crisp white formal shirt made from premium cotton. Perfect for office wear and special occasions.",
    basePrice: "45.99",
    brand: "EliteWear",
    category: "Formal",
    material: "Cotton Blend",
    pattern: "Plain",
    fit: "Slim",
    sleeve: "Long",
    rating: "4.7",
    reviewCount: 89,
    images: [whiteShirtImg],
    createdAt: new Date(),
    variants: [
      {
        id: "v5",
        productId: "2",
        color: "White",
        size: "S",
        stock: 20,
        price: "39.99",
        discountPercent: 13,
      },
      {
        id: "v6",
        productId: "2",
        color: "White",
        size: "M",
        stock: 25,
        price: "39.99",
        discountPercent: 13,
      },
      {
        id: "v7",
        productId: "2",
        color: "White",
        size: "L",
        stock: 18,
        price: "39.99",
        discountPercent: 13,
      },
    ],
  },
  {
    id: "3",
    name: "Blue Checkered Casual Shirt",
    description: "Modern checkered pattern shirt with a relaxed fit. Great for casual outings and weekend wear.",
    basePrice: "34.99",
    brand: "TrendSet",
    category: "Casual",
    material: "Cotton",
    pattern: "Checked",
    fit: "Regular",
    sleeve: "Long",
    rating: "4.3",
    reviewCount: 156,
    images: [checkeredShirtImg],
    createdAt: new Date(),
    variants: [
      {
        id: "v8",
        productId: "3",
        color: "Blue",
        size: "M",
        stock: 22,
        price: "34.99",
        discountPercent: 0,
      },
      {
        id: "v9",
        productId: "3",
        color: "Blue",
        size: "L",
        stock: 28,
        price: "34.99",
        discountPercent: 0,
      },
      {
        id: "v10",
        productId: "3",
        color: "Blue",
        size: "XL",
        stock: 16,
        price: "34.99",
        discountPercent: 0,
      },
    ],
  },
  {
    id: "4",
    name: "Black Polo Shirt",
    description: "Classic black polo shirt with comfortable cotton blend fabric. Perfect for smart casual occasions.",
    basePrice: "24.99",
    brand: "ComfortZone",
    category: "Polo",
    material: "Cotton Blend",
    pattern: "Plain",
    fit: "Regular",
    sleeve: "Short",
    rating: "4.4",
    reviewCount: 203,
    images: [poloShirtImg],
    createdAt: new Date(),
    variants: [
      {
        id: "v11",
        productId: "4",
        color: "Black",
        size: "S",
        stock: 30,
        price: "19.99",
        discountPercent: 20,
      },
      {
        id: "v12",
        productId: "4",
        color: "Black",
        size: "M",
        stock: 35,
        price: "19.99",
        discountPercent: 20,
      },
      {
        id: "v13",
        productId: "4",
        color: "Black",
        size: "L",
        stock: 25,
        price: "19.99",
        discountPercent: 20,
      },
    ],
  },
];

// Additional products for variety
export const extendedMockProducts: ProductWithVariants[] = [
  ...mockProducts,
  // Generate more products with variations
  ...Array.from({ length: 46 }, (_, i) => ({
    id: `${i + 5}`,
    name: `Shirt ${i + 5}`,
    description: `Quality shirt with modern design and comfortable fit. Product ${i + 5} in our collection.`,
    basePrice: (Math.random() * 40 + 20).toFixed(2),
    brand: ["StyleCraft", "EliteWear", "TrendSet", "ComfortZone", "FashionForward"][i % 5],
    category: ["Casual", "Formal", "Polo", "T-Shirt"][i % 4],
    material: ["Cotton", "Cotton Blend", "Linen", "Polyester"][i % 4],
    pattern: ["Plain", "Checked", "Printed", "Striped"][i % 4],
    fit: ["Slim", "Regular", "Loose"][i % 3],
    sleeve: ["Short", "Long", "3/4"][i % 3],
    rating: (Math.random() * 2 + 3).toFixed(1),
    reviewCount: Math.floor(Math.random() * 300 + 50),
    images: [navyShirtImg, whiteShirtImg, checkeredShirtImg, poloShirtImg][i % 4],
    createdAt: new Date(),
    variants: [
      {
        id: `v${i * 3 + 14}`,
        productId: `${i + 5}`,
        color: ["Red", "Blue", "Green", "White", "Black", "Gray"][i % 6],
        size: "M",
        stock: Math.floor(Math.random() * 50 + 10),
        price: (Math.random() * 40 + 20).toFixed(2),
        discountPercent: Math.random() > 0.7 ? Math.floor(Math.random() * 30 + 5) : 0,
      },
      {
        id: `v${i * 3 + 15}`,
        productId: `${i + 5}`,
        color: ["Red", "Blue", "Green", "White", "Black", "Gray"][i % 6],
        size: "L",
        stock: Math.floor(Math.random() * 50 + 10),
        price: (Math.random() * 40 + 20).toFixed(2),
        discountPercent: Math.random() > 0.7 ? Math.floor(Math.random() * 30 + 5) : 0,
      },
    ],
  })),
];

export const mockCategories = [
  { name: "Casual", count: 25 },
  { name: "Formal", count: 18 },
  { name: "Polo", count: 12 },
  { name: "T-Shirt", count: 15 },
];

export const mockFilters = {
  colors: ["Red", "Blue", "Green", "White", "Black", "Gray", "Navy", "Beige"],
  sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  materials: ["Cotton", "Cotton Blend", "Linen", "Polyester", "Silk"],
  patterns: ["Plain", "Checked", "Printed", "Striped"],
  fits: ["Slim", "Regular", "Loose"],
  sleeves: ["Short", "Long", "3/4"],
  brands: ["StyleCraft", "EliteWear", "TrendSet", "ComfortZone", "FashionForward"],
  priceRanges: [
    { label: "Under $25", min: 0, max: 25 },
    { label: "$25 - $40", min: 25, max: 40 },
    { label: "$40 - $60", min: 40, max: 60 },
    { label: "Over $60", min: 60, max: 1000 },
  ],
};